apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restworkerjava.fullname" . }}
  labels:
    app: restworkerjava
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: restworkerjava
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8100"  # Use the correct port where your app is running
      labels:
        app: restworkerjava
    spec:
      containers:
      - env:
        - name: GATEWAY_ADDRESS
          value: {{ quote .Values.container.env.gatewayAddress | default }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain}}
        - name: MAX_JOBS_ACTIVE
          value: {{ quote .Values.container.env.maxjobsactive}}
        - name: POLL_INTERVAL
          value: {{ quote .Values.container.env.pollinterval}}
        - name: TIMEOUT
          value: {{ quote .Values.container.env.timeout}}
        - name: TEST_RESPONDER_ADDRESS
          value: {{ quote .Values.container.env.testResponderAddress}}
        - name: REQUEST_TIMEOUT
          value: {{ quote .Values.container.env.requestTimeout}}

        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}