apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: restworkerjava
  labels:
    app: restworkerjava
    test: test
  namespace: worker
spec:
  selector:
    matchLabels:
      app: restworkerjava
  endpoints:
  - path: /actuator/prometheus
    interval: 10s
    port: http
