{
 "title": "restworkerjava",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (irate(restworkerjava_jobs_started_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Finished",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (irate(restworkerjava_jobs_finished_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}