apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.DeploymentName }}
  labels:
    {{- include "measuring-endpoints.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: measuring-endpoints
  template:
    metadata:  
      labels:
        app: measuring-endpoints
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain}}
        - name: RESPONSEDELAY
          value: {{ quote .Values.responseDelay}}
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
        resources: {}

