# For entire chart see:
# https://github.com/sustainable-computing-io/kepler-helm-chart/blob/main/chart/kepler/values.yaml

# -- Extra environment variables
# extraEnvVars:
#  KEPLER_LOG_LEVEL: "1"
#  ENABLE_GPU: "true"
#  ENABLE_EBPF_CGROUPID: "true"
#  EXPOSE_IRQ_COUNTER_METRICS: "true"
#  EXPOSE_KUBELET_METRICS: "true"
#  ENABLE_PROCESS_METRICS: "true"
#  CPU_ARCH_OVERRIDE: ""
#  CGROUP_METRICS: "*"
  # REDFISH_PROBE_INTERVAL_IN_SECONDS: "60"
  # REDFISH_SKIP_SSL_VERIFY: "true"

# serviceMonitor:
#   interval: 15s