apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: camunda-8-print-worker
  template:
    metadata:
      labels:
        app: camunda-8-print-worker
    spec:
      containers:
      - env:
        - name: GATEWAY_ADDRESS
          value: {{ quote .Values.container.env.gatewayAddress}}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain}}
        - name: TEST_RESPONDER_ADDRESS
          value: {{ quote .Values.container.env.testResponderAddress}}
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}